# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearest_elementary',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='street',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
